apiVersion: v1
kind: Pod
metadata:
  name: web-color2
  labels:
   app: web
spec:
  containers:
  - name: web-color
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: blue

